### ISSUE TITLE
浏览照片点击图片放大的过程中  有那么一秒 会遮盖上下分页数字和pageControlView

### ISSUE THREAD

**Issue by kinghour** [LuKane/KNPhotoBrower#11]

**Comment by kinghour** [comment]
找到具体原因了  当我选择的图片比较大  占全全屏的时候  图片放大过程中会遮住上下pageControl  当图片较小的  进入图片预览放大的过程中  便不会出现  应该就是在图片尺寸大小和全屏幕布局上微全面遮住了上下pagecontrol

**Comment by LuKane** [comment]
恩. 我这边也会做相应的修改
