### ISSUE TITLE
图片在左右滑动的时候出现了变形

### ISSUE THREAD

**Issue by YufengHu123** [LuKane/KNPhotoBrower#12]

**Comment by LuKane** [comment]
请问在哪个控制器中发现的!!

**Comment by LuKane** [comment]
已经解决~~ 请更新最新代码

**Comment by YufengHu123** [comment]
谢谢！刚看到，我改了下你的代码可以了。





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：LuKane<notifications@github.com>
时间：2018年4月10日 上午10:34:01
收件人：LuKane/KNPhotoBrower<KNPhotoBrower@noreply.github.com>
抄送：YufengHu<iosyufeng@sina.com>,Author<author@noreply.github.com>
主题：Re: [LuKane/KNPhotoBrower] 图片在左右滑动的时候出现了变形 (#12)

已经解决~~ 请更新最新代码
