### ISSUE TITLE
图片异常

### ISSUE THREAD

**Issue by BIPOliu** [LuKane/KNPhotoBrower#16]
我的sourseview设置了UIViewContentModeScaleAspectFit，浏览器消失的时候，图片异常

**Comment by LuKane** [comment]
你这边是 长图的时候 异常吗? 还是 怎么个问题?

**Comment by BIPOliu** [comment]
设置了uiviewmodel之后，缩略图显示全部的尺寸






在 2018-07-30 16:41:51，"LuKane" <notifications@github.com> 写道：


你这边是 长图的时候 异常吗? 还是 怎么个问题?

**Comment by LuKane** [comment]
没有明白你的意思! 你直接贴代码吧!!! 把你设置的代码模块贴出来!

**Comment by LuKane** [comment]
感觉你的意思是 :  测试控制器界面所写的!!! 那个是由你这边自己定义的! 如果有其他的不明白的地方加QQ细聊

**Comment by BIPOliu** [comment]
self.attachImg.image = x;

self.attachImg.contentMode = UIViewContentModeScaleAspectFit;

    [self.attachImgmas_makeConstraints:^(MASConstraintMaker *make) {

        make.left.mas_equalTo(20);

        make.height.mas_equalTo(34);

        make.width.mas_equalTo(40);

        make.centerY.mas_equalTo(0);

    }];



在tableview上一个cell一个缩略图，只有在contentMode = UIViewContentModeScaleAspectFit;的情况下，显示出问题，还有个问题，如果cell里的图片没加载出来，浏览器可以正常显示吗


在 2018-08-02 15:29:07，"LuKane" <notifications@github.com> 写道：


没有明白你的意思! 你直接贴代码吧!!! 把你设置的代码模块贴出来!

**Comment by LuKane** [comment]
加QQ说吧!! 我这边没问题

**Comment by BIPOliu** [comment]
994291909

在 2018-08-03 18:32:41，"LuKane" <notifications@github.com> 写道：


加QQ说吧!! 我这边没问题
