### ISSUE TITLE
图片单张的时候以及有时候图片莫名点进去扩大了

### ISSUE THREAD

**Issue by VaeXnn** [LuKane/KNPhotoBrower#2]
单张图片的时候返回动画很生硬,以及有时候放大图片返回后点击进去那张图片会莫名变大,滚动查看其它图片又变正常了

**Comment by LuKane** [comment]
感谢你的问题提出.
1.单张图片时,如果是GIf图,这次已经修改. 如果图片在屏幕外面, 则消失掉,不做动画
2.放大图片返回后点击进去那张图片会莫名变大,希望您能在真机上测试一下.如果还是有问题,再次 Issues一下.谢谢

**Comment by LuKane** [comment]
现已修改了这个bug,感谢您的问题提出,谢谢
