### ISSUE TITLE
图片打开问题

### ISSUE THREAD

**Issue by iMaBiao** [LuKane/KNPhotoBrower#3]
1、打开第二张图片的时候总会先显示第一张图片，然后再变成第二张；
2、关闭预览的时候，总是会回到第一张图片的位置

**Comment by LuKane** [comment]
亲, 请问一下, 您选择的是哪个 界面?  ViewController ,NineSquareController, ScrollViewController,CollectionViewController 中的哪一个?不然我一脸懵逼啊

**Comment by iMaBiao** [comment]
ViewController

**Comment by LuKane** [comment]
亲, 先问下您的代码是不是最新的代码!? 如果是最新的代码, 那么就没问题啊.
ViewController : 9空格图片展示, 还有一张放在控制器View的最上方, 是看不到的. 所以总共10张图片.
如果还是有问题, 建议 清理一下XCode资源, 顺便将 模拟器上的App 卸载掉, 重新运行.. 最后希望您那边不会出现问题

**Comment by iMaBiao** [comment]
OK，谢谢
