### ISSUE TITLE
也是图片显示问题

### ISSUE THREAD

**Issue by aaluyi** [LuKane/KNPhotoBrower#4]
和上个同学遇到一样的问题，他是ViewController控制器，我这是在CollectionView控制器，你原来是10张图片，一个界面就展示全了，没有cell重用，我自己又添加了几张图片让cell实现重用，进入collectionVIew页面之后，一开始什么都正常，点哪张从哪张位置放大，可以滚动缩放，单击缩小并返回原来的位置，可是当我将collectionView拉倒底部再回滚到顶部的时候，点击重用的cell显示图片就是乱的，比如说点的第三个cell，图片从第二个位置开始放大，最终显示的图片是对的，缩小回去的时候回到的也是第二个cell的位置，另外也不是每张图片都变成这样，有的是正常的，有的就会出现上面的问题。
PS：最近在做的工程有类似相册展示的功能，看到作者的demo很给力就想复用一下，途中遇到一点问题，描述的比较冗余，如果作者能看到，希望帮忙解答一下，万分感谢！

**Comment by LuKane** [comment]
已经看到您的issue了. 我会尽快解决您的问题的

**Comment by aaluyi** [comment]
好的，谢谢

**Comment by LuKane** [comment]
问题已经解决... 请下载最新的Demo , 那里面有详细的解决方案.. 谢谢

**Comment by aaluyi** [comment]
有劳前辈了，谢谢

**Comment by aaluyi** [comment]
前辈，我看demo里图片的url传到了KNPhotoBrower这个类里面，url用的蛮多的，我现在想展示本地下载完成的图片，要改动的话，改动大吗

**Comment by LuKane** [comment]
如果全部改成本地图片... 工作量大约在半天时间..

**Comment by aaluyi** [comment]
好的，谢谢

**Comment by LuKane** [comment]
已经改完. 注意查看就好.欢迎点赞☺

**Comment by aaluyi** [comment]
前辈，你这太热心了，万分感谢，已点赞

**Comment by mingxuler** [comment]
这个框架好用，现在我也遇到复用问题，点击的时候复用cell，我下面两句代码没写，是不是这个原因。然后还有就是，我的collectionView 分了两组我写了下面的后  报错-[UIView image]: unrecognized selector sent to instance 0x1557c0cb0
[photoBrower setDataSourceUrlArr:[self.collectionPrepareArr copy]];
  [photoBrower setSourceViewForCellReusable:_collectionView];

这个我该怎么解决的呀，希望你能到，给个建议

**Comment by LuKane** [comment]
目前Demo中 是以一个组的形式完成功能的.
单纯以一个分组完成功能的话,需要加上
[photoBrower setDataSourceUrlArr:[self.collectionPrepareArr copy]];
[photoBrower setSourceViewForCellReusable:_collectionView];
这两句代码.
 不支持两个分组一起实现功能,可以考虑用单个分组完成功能

**Comment by mingxuler** [comment]
谢谢你的呀大神，

现在单个分组复用用着是没问题从网络加载，前半部分没问题网络加载按照你的示例没问题，但是点击后半部分本地就有问题，但是不用那个[photoBrower setDataSourceUrlArr:[self.collectionPrepareArr copy]];
> [photoBrower setSourceViewForCellReusable:_collectionView];就可以出现，可以显示，但是偶尔会有复用问题。
> 
这个是didSelect 里面一部分代码还有图片截图，然后那些左上角有黄色x的图片是刚刚添加本地图片，我是让他点击不同地方都可以查看大图

**Comment by LuKane** [comment]
你加我QQ,详细说下. 1169604556
