### ISSUE TITLE
iOS 10.0以上BUG

### ISSUE THREAD

**Issue by Fgoson** [LuKane/KNPhotoBrower#8]
突然发现iOS 10.0以上放大图片，划动到下一个图片，前面放大的图片没有变回原来的大小

**Comment by LuKane** [comment]
请问是每次都复现这个问题吗!?

**Comment by LuKane** [comment]
同学你好 , 问题已经解决  更新代码即可. 如有其他问题, 还麻烦您指出,谢谢

**Comment by Fgoson** [comment]
谢谢^_^
