### ISSUE TITLE
使用新版SDWebImage下载图不会显示圆形进度条

### ISSUE THREAD

**Issue by liuyaquan** [LuKane/KNPhotoBrower#9]
首先感谢作者无私奉献源码, 在使用新版SDWebImage下载图不会显示圆形进度条,我使用的是新版SDWebImage4.0, 在下载图片的时候不会显示进度,  换成你项目中的SDWebImage版本就可以,  不知道是我用法错了还是什么原因,  希望作者回复.

**Comment by LuKane** [comment]
收到. 下班回家再看看吧!! 不要着急

**Comment by LuKane** [comment]
新版SDWebImage 在加载gif图片的时候,需要修改很多东西, 我这边等有时间再去修改.. 
如果你那边不需要加载gif的话,则 在 ImageView 中 
progressHUD.progress = progress; // 设置 进度 这段代码 ,你要放在 异步的主线中执行就OK了

**Comment by liuyaquan** [comment]
解决了  谢谢
